### PR TITLE
fix: Specify exact regex when adding in h2 tags for title

### LINKED ISSUE #135: Cleanup HTML functionality adding in unnecessary H2 tags
#### Environment details

  - Programming language: Java
  - OS: Linux
  - Language runtime version: Java 11
  - Package version: v1.6.0

#### Steps to reproduce

Tha YAMLUtil.cleanupHTML function is replacing the `==` blocks with h2 tags: 
https://github.com/googleapis/java-docfx-doclet/blob/main/third_party/docfx-doclet-143274/src/main/java/com/microsoft/util/YamlUtil.java#L38

This is causing errors in the EnvironmentsClient.java file in java-orchestration-airflow: 
https://github.com/googleapis/java-orchestration-airflow/blob/main/google-cloud-orchestration-airflow/src/main/java/com/google/cloud/orchestration/airflow/service/v1/EnvironmentsClient.java#L525-L542

`
This replaces "scikit-learn":"==0.19.0" to "scikit-learn":"<h2>0.19.0" and "botocore":"==1.7.14" to "botocore":"</h2>1.7.14"
`

The added h2 tags is invalid HTML and the javadoc is throwing errors.

### PR DESCRIPTION
**Pull request by lqiu96**
Fixes [#135](https://github.com/googleapis/java-docfx-doclet/issues/135)

> It's a good idea to open an issue first for discussion.

- [ x ] Tests pass
- [ x ] Appropriate changes to README are included in PR

### CODE REVIEW

File: third_party/docfx-doclet-143274/src/test/java/com/microsoft/util/YamlUtilTest.java [hunk 1]
```diff
@@ -127,7 +127,12 @@ public void cleanupHtmlEqualTitlesTest() {
         assertEquals(expectedResult, YamlUtil.cleanupHtml(expectedActual));
         assertEquals(random + expectedResult + random, YamlUtil.cleanupHtml(random + expectedActual + random));
         assertEquals(expectedResult + random + expectedResult, YamlUtil.cleanupHtml(expectedActual + random + expectedActual));
+
         assertEquals("= text =", YamlUtil.cleanupHtml("= text ="));
+        assertEquals("==testing==", YamlUtil.cleanupHtml("==testing=="));
```
Comment (suztomo) [inline third_party/docfx-doclet-143274/src/test/java/com/microsoft/util/YamlUtilTest.java:132]: I would put `"scikit-learn":"==0.19.0"` thing as a test case.

**Review by suztomo — DISMISSED** [review]

File: third_party/docfx-doclet-143274/src/test/java/com/microsoft/util/YamlUtilTest.java (hunk 1 above)
Comment (lqiu96) [reply third_party/docfx-doclet-143274/src/test/java/com/microsoft/util/YamlUtilTest.java:132]: Ah yes! I'll add that

**Review by suztomo — APPROVED** [review]
